# This is a sample build configuration for Docker.
# Check our guides at https://confluence.atlassian.com/x/O1toN for more examples.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
image: rpalacio86/compose-heroku:latest

pipelines:
  branches:
    master:
      - step:
          name: Build and Test
          caches:
            - docker
          services:
            - docker
          script: # Modify the commands below to build your repository.
            # Set $DOCKER_HUB_USERNAME and $DOCKER_HUB_PASSWORD as environment variables in repository settings
            - export IMAGE_NAME=amdocs/sampleci:$BITBUCKET_COMMIT

            # build the Docker image (this will use the Dockerfile in the root of the repo)
            - docker-compose --file docker-compose.test.yml build
            # authenticate with the Docker Hub registry
            - docker-compose --file docker-compose.test.yml run sut
            # push the new Docker image to the Docker registry
            # - docker push $IMAGE_NAME
      - step:
          name: Build and deploy to stage
          caches:
            - docker
          services:
            - docker
          script:
            # Build the image
            - docker-compose build api-prod
            # Push docker image to heroku registry 
            - docker login --username=_ --password=$HEROKU_API_KEY registry.heroku.com
            # Rename image to match heroku requirement
            - docker tag amdocs/sampleci registry.heroku.com/$HEROKU_STAGE/web
            # Push the image to the Heroku registry
            - docker push registry.heroku.com/$HEROKU_STAGE/web
            - heroku container:login
            # Deploy the pushed image
            - heroku container:release web -a $HEROKU_STAGE
