# This is a sample build configuration for Docker.
# Check our guides at https://confluence.atlassian.com/x/O1toN for more examples.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
image: docker/compose:latest

pipelines:
  default:
    - step:
        services:
          - docker
        script: # Modify the commands below to build your repository.
          # Set $DOCKER_HUB_USERNAME and $DOCKER_HUB_PASSWORD as environment variables in repository settings
          - export IMAGE_NAME=rpalacio86/sampleci:$BITBUCKET_COMMIT

          # build the Docker image (this will use the Dockerfile in the root of the repo)
          - docker-compose --file docker-compose.test.yml build
          # authenticate with the Docker Hub registry
          - docker-compose --file docker-compose.test.yml run sut
          # push the new Docker image to the Docker registry
          # - docker push $IMAGE_NAME
