version: '3.8'

services: 
  api-prod:
    image: claro/sampleci
    build: .
    ports:
      - "3000:3000"
    environment: 
      NODE_ENV: production
      PORT: 3000
  api-test:
    image: claro/sampleci-test
    build: .
    ports:
      - "3001:30001"
    environment: 
      NODE_ENV: test
      PORT: 3001
    command: npm test
